### ISSUE TITLE
[Bug]: byte array coercion on json marshaling causes invalid formatting

### ISSUE THREAD

**Issue by GuyARoss** [pkgz/websocket#16]
#### Issue description
When using the servers `Emit` function with a byte array as the data argument, the connection's emit function will not coerce the byte array back into a string.   

#### Steps to reproduce the issue

1.  Use the socket's top-level `Emit` function.
```go
wsServer := websocket.Start(context.Background())
wsServer.Emit("test", []byte("working?"))
```
2.  Connect with a client, and await the emit request.
3.  View the emit response on the client. 

#### What's the expected result?
- Expected result would be a valid string representative of the actual string passed into the data field.

#### What's the actual result?
- JSON marshalled byte array

#### Proposed solution(s)
1. On server run, cast the `msg.Data` to a string
```go
c.Emit(msg.Name, string(msg.Data))
```
2. Use a string as the data argument. 
```go
func (s *Server) Emit(name string, data string) { ... 
```
3. Continue to support the same interface as the connection for the socket server.
```go
func (s *Server) Emit(name string, data interface{}) { ... 
```

#### Additional details / screenshot
![Screenshot from 2021-09-02 01-59-45](https://user-images.githubusercontent.com/21269957/131790085-ab4c467d-0345-469b-92fc-cbb1d493239a.png)

**Comment by exelban** [comment]
Hi. Thanks for reporting.
Sorry for the long response. I will take a look at this bug.

**Comment by exelban** [comment]
Ok. I know this case.
It cannot be fixed with 2 way because I mostly using a ws to send structures. And with string will be a little bit complicated.
Now about the third way. It has another problem. When you passing a struct to Emit as the interface on another side you will receive a map in `Message.Data`. And it will require additional unmarshalling.

**Comment by exelban** [comment]
The second problem appears only when ws talking with another golang ws (not js).
Because when you sending `{field: "test"}` - in js it will be shown as a string. But in go it will be map[field: test].
And to parse it to the struct you will need to make marshal to bytes and then unmarshal to a wanted struct.

**Comment by GuyARoss** [comment]
Cool, @exelban so to clarify, we should go with solution no. 3?

**Comment by exelban** [comment]
As I say, the third (3) one could not be implemented.

**Comment by GuyARoss** [comment]
Okay, so how would you like to solve this?

**Comment by exelban** [comment]
Yes, but I don't have the solution.

**Comment by GuyARoss** [comment]
So, leave the bug?

**Comment by exelban** [comment]
It's not really the bug. I don't have a solution for this that will not break the use cases that I need.

**Comment by GuyARoss** [comment]
@exelban How is this not a bug? This issue renders socket emitting at socket level entirely broken.
